# Generated by Django 4.2.2 on 2024-02-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_model',
            old_name='esallay',
            new_name='esallary',
        ),
    ]
