# Generated by Django 4.2.2 on 2024-03-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javaquiz',
            name='category',
            field=models.CharField(default='java', max_length=50),
        ),
        migrations.AlterField(
            model_name='pythonquiz',
            name='category',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
