# Generated by Django 4.2.2 on 2024-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_javaquiz_category_alter_pythonquiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javaquiz',
            name='category',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
