# Generated by Django 4.2.2 on 2024-02-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_student_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=40)),
                ('SmobileNo', models.IntegerField()),
                ('Saddress', models.CharField(max_length=50)),
                ('ScourseName', models.CharField(max_length=50)),
            ],
        ),
    ]
