# Generated by Django 4.2.2 on 2024-02-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_student_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_enrollment',
            name='SmobileNo',
            field=models.BigIntegerField(),
        ),
    ]
