# Generated by Django 4.2.2 on 2024-02-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='senrollment_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=39)),
                ('course', models.CharField(max_length=40)),
                ('mobile_no', models.BigIntegerField()),
                ('Date', models.DateField(default='datetime.datetime.now()')),
            ],
        ),
    ]
