# Generated by Django 4.2.2 on 2024-02-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='senrollment_form',
            new_name='senrollment_model',
        ),
    ]
