# Generated by Django 4.2.2 on 2024-02-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_student_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendence',
            name='attendence',
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='Branch',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='Attendence',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
