# Generated by Django 4.2.2 on 2024-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=40)),
                ('Lname', models.CharField(max_length=40)),
                ('password', models.IntegerField()),
                ('rpassword', models.IntegerField()),
            ],
        ),
    ]
